"""empty message

Revision ID: 3783a03a1757
Revises: d57c035c674a
Create Date: 2020-11-20 06:36:20.047374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3783a03a1757'
down_revision = 'd57c035c674a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carrier', sa.Column('active', sa.Boolean(), nullable=True))
    op.add_column('packager', sa.Column('active', sa.Boolean(), nullable=True))
    
    op.execute('UPDATE carrier SET active = True WHERE active IS NULL;')
    op.execute('UPDATE shipment SET active = True WHERE active IS NULL;')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('packager', 'active')
    op.drop_column('carrier', 'active')
    # ### end Alembic commands ###
